name: Build Android Application

on:
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up OpenJDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle Build System
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Unit Tests
        run: ./gradlew test

      - name: Generate Debug APK
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'}}
        run: ./gradlew assembleDebug

      - name: Upload Debug APK Artifact
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'}}
        uses: actions/upload-artifact@v3
        with:
          name: MusicClock
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Generate Release APK
        if: ${{ github.event_name == 'release' }}
        run: ./gradlew assembleRelease

      - name: Upload Release APK Artifact
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-artifact@v3
        with:
          name: MusicClock
          path: app/build/outputs/apk/release/app-release.apk
